In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
from sklearn.preprocessing import StandardScaler as stdscl
import matplotlib.pyplot as plt
from google.colab import drive
import datetime
import seaborn as sns
from collections import Counter
import math
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Assingment/Binary_Classification'
train = pd.read_csv(path + '/train.csv')
test = pd.read_csv(path + '/test.csv')

Mounted at /content/drive


In [ ]:
print(train.columns)
corr = train.corr()['label']
print(corr.sort_values(ascending=False))

Index(['Unnamed: 0', 'column_a', 'column_c', 'column_d', 'column_e',
       'column_f', 'column_g', 'column_h', 'column_i', 'column_j', 'column_k',
       'column_l', 'column_m', 'column_n', 'column_o', 'column_p', 'column_q',
       'column_r', 'column_s', 'column_t', 'column_u', 'column_v', 'column_w',
       'column_x', 'column_y', 'column_z', 'column_aa', 'column_ab',
       'column_ac', 'column_ad', 'column_ae', 'column_af', 'column_ag',
       'column_ah', 'label'],
      dtype='object')
label         1.000000
column_e      0.516561
column_c      0.495724
column_a      0.464405
column_g      0.423568
column_ae     0.297356
column_i      0.282805
column_ag     0.227841
column_h      0.224986
column_ac     0.207162
column_f      0.205889
column_o      0.198936
column_p      0.181974
column_u      0.180405
column_m      0.174353
column_r      0.152008
column_n      0.144603
column_w      0.136564
column_k      0.135041
column_y      0.133619
column_j      0.130556
column_l      0.12

In [ ]:
#X_train = train.drop(columns=['label', 'Unnamed: 0', 'column_q', 'column_ab', 'column_t', 'column_z'])
X_train = train.drop(columns=['label','Unnamed: 0'])
y_train = train['label']
#X_test = test.drop(columns=['Unnamed: 0', 'column_q', 'column_ab', 'column_t', 'column_z'])
X_test = test.drop(columns=['Unnamed: 0'])

In [ ]:
def Binary_classificatio(X, y):
  model = LogisticRegression()
  model.fit(X, y)
  return model

def Performence(model, X, y):
  y_pred = model.predict(X)
  accuracy = metrics.accuracy_score(y, y_pred)
  f1 = f1_score(y, y_pred)
  return y_pred, accuracy, f1

In [ ]:
model = Binary_classificatio(X_train, y_train)
y_pred, accuracy, f1 = Performence(model, X_train, y_train)
print(y_pred, accuracy, f1)

[1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1
 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 0 0 1 0
 1 1 1 1 0 1 1 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 1
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 1
 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0
 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 1 1 0 1 0
 1 1 0 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 0 1 0 1] 0.9224489795918367 0.9389067524115755


In [ ]:
Prediction =  model.predict(X_test)
A, = Prediction.shape
Id = np.arange(A)
df = pd.DataFrame({'ID': Id, 'label': Prediction})
csv_file = '/content/drive/MyDrive/Assingment/Binary_Classification/Arun_Dilli_Submission.csv'
df.to_csv(csv_file, index=False)

In [ ]:
# Define a global variable
global_var = 42

# Access the global symbol table using globals()
global_symbols = globals()

# Print the global symbol table
print(global_symbols)

# Access a specific global variable from the symbol table
#print(global_symbols['global_var'])


{'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', 'https://www.kaggle.com/code/metric/event-detection-ap?scriptVersionId=141456876&cellId=1', 'x = 5\nassert x == 5, "x should be equal to 5"', 'x = 4\nassert x == 5, "x should be equal to 5"', "# Define a global variable\nglobal_var = 42\n\n# Access the global symbol table using globals()\nglobal_symbols = globals()\n\n# Print the global symbol table\nprint(global_symbols)\n\n# Access a specific global variable from the symbol table\nprint(global_symbols['global_var'])", "# Define a global variable\nglobal_var = 42\n\n# Access the global symbol table using globals()\nglobal_symbols = globals()\n\n# Print the global symbol table\nprint(global_symbols)\n\n# Access a specific global variable from the symbol table\n#print(glo

In [ ]:
import torch
empty_tensor = torch.empty(2, 3)  # Creates a 2x3 uninitialized tensor
print(empty_tensor)
zero_tensor = torch.zeros(3, 2)  # Creates a 3x2 tensor filled with zeros
print(zero_tensor)
data = [1, 2, 3, 4]
from_list = torch.tensor(data)
print(from_list)


tensor([[-2.4774e-19,  4.3234e-41, -2.4774e-19],
        [ 4.3234e-41,  4.4842e-44,  0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([1, 2, 3, 4])


In [ ]:
from tqdm import tqdm
import time

# Create a list to iterate over
data = range(10)

# Wrap the iterable with tqdm
for item in tqdm(data, desc="Arun"):
    # Simulate some work
    time.sleep(0.5)


Arun: 100%|██████████| 10/10 [00:05<00:00,  1.99it/s]
